export default {
  countryMapping: {
    ßHU: ['Hungary', 'HUN'],
    LT: ['Lithuania', 'LTU'],
    TR: ['Turkey', 'TUR'],
    BG: ['Bulgaria', 'BGR'],
    GR: ['Greece', 'GRC'],
    CZ: ['Czechia', 'CZE'],
    AT: ['Austria', 'AUT'],
    IE: ['Ireland', 'IRL'],
    EE: ['Estonia', 'EST'],
    SK: ['Slovakia', 'SVK'],
    RO: ['Romania', 'ROU'],
    BE: ['Belgium', 'BEL'],
    PL: ['Poland', 'POL'],
    NO: ['Norway', 'NOR'],
    SE: ['Sweden', 'SWE'],
    DE: ['Germany', 'DEU'],
    FI: ['Finland', 'FIN'],
    GB: ['United Kingdom', 'GBR'],
    LI: ['Liechtenstein', 'LIE'],
    HR: ['Croatia', 'HRV'],
    NL: ['Netherlands', 'NLD'],
    SI: ['Slovenia', 'SVN'],
    ES: ['Spain', 'ESP'],
    CH: ['Switzerland', 'CHE'],
    IT: ['Italy', 'ITA'],
    FR: ['France', 'FRA'],
    DK: ['Denmark', 'DNK'],
    MT: ['Malta', 'MLT'],
    LU: ['Luxembourg', 'LUX'],
    IS: ['Iceland', 'ISL'],
    LV: ['Latvia', 'LVA'],
    CY: ['Cyprus', 'CYP'],
    PT: ['Portugal', 'PRT'],
  },
};
